from enum import Enum

class EventType(Enum):
    YELLOW_CARD = "YELLOW_CARD"
    RED_CARD = "RED_CARD"
    GOAL = "GOAL"
    CORNER = "CORNER"
    FOUL_DEFENSIVE_HALF = "FOUL_DEFENSIVE_HALF"
    FOUL_ATTACKING_HALF = "FOUL_ATTACKING_HALF"
    ANNULLED_GOAL = "ANNULLED_GOAL"
    HIT_WOODWORK = "HIT_WOODWORK"
    GOALKEEPER_SAVE = "GOALKEEPER_SAVE"
    PENALTY = "PENALTY"

