select t.MINUTE_SECOND_STARTED, t.MINUTE_SECOND_FINISHED, te.ID_CRITERION, te.EVENT, te.MINUTE_SECOND / 60 as MINUTE, te.MINUTE_SECOND % 60 as SECOND, te.DESCRIPTION, te.team, c.title AS CRITERION_TITLE from
TIMELINES t join TIMELINE_EVENTS te
on t.id = te.ID_TIMELINE
left join CRITERIA c
on te.ID_CRITERION = c.id
where t.id = 2
order by te.MINUTE_SECOND asc