CREATE UNIQUE INDEX ux_timeline_minute_null
ON TIMELINE_EVENTS(MINUTE_SECOND, ID_TIMELINE)
WHERE ADDITIONAL_MINUTE_SECOND IS NULL;

CREATE UNIQUE INDEX ux_apenas_um_null
ON TIMELINES ((1))
WHERE MINUTE_SECOND_FINISHED IS NULL;

PRAGMA index_list('TIMELINE_EVENTS');
PRAGMA index_list('TIMELINES');